# Generated by Django 2.1.3 on 2018-11-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(3, 'Comedy'), (4, 'Sci-fi'), (6, 'Fantasy'), (2, 'Drama'), (1, 'Horror'), (5, 'Thiller'), (7, 'Document')]),
        ),
    ]
