# Generated by Django 2.1.3 on 2018-11-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181121_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (3, 'Comedy'), (1, 'Horror'), (4, 'Sci-fi'), (6, 'Fantasy'), (5, 'Thiller'), (2, 'Drama'), (7, 'Document')], default=0),
        ),
    ]
