# Generated by Django 2.1.3 on 2018-11-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181121_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(5, 'Thiller'), (3, 'Comedy'), (2, 'Drama'), (1, 'Horror'), (7, 'Document'), (0, 'Nieznany'), (6, 'Fantasy'), (4, 'Sci-fi')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
