# Generated by Django 2.1.3 on 2018-11-23 12:13

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181121_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='movie',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(0, 'Nieznany'), (1, 'Horror'), (7, 'Document'), (3, 'Comedy'), (5, 'Thiller'), (6, 'Fantasy'), (4, 'Sci-fi'), (2, 'Drama')], default=0),
        ),
    ]
