# Generated by Django 2.1.3 on 2018-11-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181123_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='czas_trwnia',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(6, 'Fantasy'), (4, 'Sci-fi'), (7, 'Document'), (3, 'Comedy'), (2, 'Drama'), (5, 'Thiller'), (0, 'Nieznany'), (1, 'Horror')], default=0),
        ),
    ]
