# Generated by Django 2.1.3 on 2018-11-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181123_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='nick',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='czas_trwnia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(1, 'Horror'), (3, 'Comedy'), (0, 'Nieznany'), (4, 'Sci-fi'), (2, 'Drama'), (5, 'Thiller'), (6, 'Fantasy'), (7, 'Document')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=5, max_length=10),
        ),
    ]
