# Generated by Django 2.1.3 on 2018-11-23 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181123_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(6, 'Fantasy'), (1, 'Horror'), (3, 'Comedy'), (7, 'Document'), (5, 'Thiller'), (2, 'Drama'), (4, 'Sci-fi'), (0, 'Nieznany')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
