# Generated by Django 2.1.3 on 2018-11-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181123_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(7, 'Document'), (3, 'Comedy'), (2, 'Drama'), (4, 'Sci-fi'), (6, 'Fantasy'), (5, 'Thiller'), (1, 'Horror'), (0, 'Nieznany')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.Movie'),
        ),
    ]
