# Generated by Django 2.1.3 on 2018-11-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181123_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(2, 'Drama'), (6, 'Fantasy'), (4, 'Sci-fi'), (0, 'Nieznany'), (3, 'Comedy'), (7, 'Document'), (5, 'Thiller'), (1, 'Horror')], default=0),
        ),
    ]
