# Generated by Django 2.1.3 on 2018-11-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20181123_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(1, 'Horror'), (2, 'Drama'), (7, 'Document'), (4, 'Sci-fi'), (3, 'Comedy'), (6, 'Fantasy'), (0, 'Nieznany'), (5, 'Thiller')], default=0),
        ),
    ]
