# Generated by Django 2.1.3 on 2018-12-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20181212_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(5, 'Thiller'), (7, 'Document'), (3, 'Comedy'), (1, 'Horror'), (6, 'Fantasy'), (0, 'Nieznany'), (4, 'Sci-fi'), (2, 'Drama')], default=0),
        ),
    ]
